import 'dart:typed_data';
import 'event.dart';

/// Context information for a table change event
///
/// Wraps an [Event] with access to the SpacetimeDB client, providing
/// convenience methods and helpers for common operations.
///
/// The context allows event handlers to:
/// - Access transaction metadata (timestamp, reducer name, caller, etc.)
/// - Check if the transaction was initiated by the current client
/// - Access the database and reducer APIs through convenience getters
///
/// Example:
/// ```dart
/// noteTable.insertEventStream.listen((event) {
///   final ctx = event.context;
///
///   if (ctx.isMyTransaction) {
///     print('I created this note!');
///   } else {
///     print('Someone else created this note');
///   }
///
///   // Access event metadata
///   if (ctx.event is ReducerEvent) {
///     final reducerEvent = ctx.event as ReducerEvent;
///     print('Reducer: ${reducerEvent.reducerName}');
///   }
/// });
/// ```
class EventContext {
  /// The SpacetimeDB client instance
  ///
  /// Stored as dynamic to avoid circular dependency issues.
  /// In practice, this will always be a SpacetimeDbClient instance
  /// generated by the code generator.
  final dynamic client;

  /// The event that triggered this context
  final Event event;

  EventContext({
    required this.client,
    required this.event,
  });

  /// 🌟 GOLD STANDARD: DX Helper - Check if this event was triggered by current client
  ///
  /// Returns true if this transaction was initiated by the current connection.
  /// This is a common check that would otherwise require verbose boilerplate.
  ///
  /// Returns false if:
  /// - Event is not a ReducerEvent
  /// - Either connection ID is null
  /// - Connection IDs don't match
  ///
  /// Example:
  /// ```dart
  /// noteTable.insertEventStream.listen((event) {
  ///   if (event.context.isMyTransaction) {
  ///     print('I created this note!');
  ///     // Maybe show a success toast
  ///   } else {
  ///     print('Someone else created this note');
  ///     // Maybe show a notification
  ///   }
  /// });
  /// ```
  bool get isMyTransaction {
    // Only ReducerEvents have caller connection IDs
    if (event is! ReducerEvent) return false;

    final reducerEvent = event as ReducerEvent;

    // Get my connection ID from the client
    // Using dynamic access since client type is dynamic to avoid circular deps
    final myConnectionId = client.connection?.connectionId;
    final callerConnectionId = reducerEvent.callerConnectionId;

    // Handle null cases
    if (myConnectionId == null || callerConnectionId == null) return false;

    // Compare byte arrays for equality
    return _bytesEqual(myConnectionId, callerConnectionId);
  }

  /// Helper to compare two byte arrays for equality
  ///
  /// Returns true if both arrays are non-null and contain identical bytes
  /// in the same order. Returns false if either is null or lengths differ.
  static bool _bytesEqual(Uint8List? a, Uint8List? b) {
    if (a == null || b == null) return false;
    if (a.length != b.length) return false;

    for (int i = 0; i < a.length; i++) {
      if (a[i] != b[i]) return false;
    }

    return true;
  }
}
